export { BackgroundEffectProvider, useBackgroundEffect, useBackgroundEffectOptional } from './BackgroundEffectProvider'
export { default as BackgroundScene } from './BackgroundScene'
export { default as EffectSelector, ReducedMotionToggle } from './EffectSelector'
export { default as RainEffect } from './RainEffect'
export { default as SnowEffect } from './SnowEffect'
export { default as SparkleEffect } from './SparkleEffect'
export { default as HeartsEffect } from './HeartsEffect'
export { default as StarsEffect } from './StarsEffect'
export { default as AuroraEffect } from './AuroraEffect'
export { default as BubblesEffect } from './BubblesEffect'
export { default as FirefliesEffect } from './FirefliesEffect'
export * from './constants'
